#!/bin/bash

set -euo pipefail
IFS=

set -x

cd

ln -s /opt/chj/emacs/.emacs

mkdir .xemacs/ || true
ln -s /opt/chj/xemacs/init.el .xemacs/

ln -s /opt/chj/emacs/.emacs.d

lesskey

(
    umask 077
    mkdir -p tmp .ssh DROP
)

chmod a+wxt,g+s DROP
touch .ssh/authorized_keys
chmod go-w .ssh/authorized_keys

set +x
echo done.
