#!/bin/bash

set -euo pipefail
IFS=

if [ "$(readlink -f .)" != "$(readlink -f ~)" ]; then
    if [ "$(readlink -f .)" != "$(readlink -f "$(dirname "$0")")" ]; then
	echo "$0: must be run from home dir or from $(dirname "$0"). Terminating."
	exit 1
    fi
fi

set -x

ln -s /opt/chj/emacs/.emacs

mkdir .xemacs/ || true
ln -s /opt/chj/xemacs/init.el .xemacs/

ln -s /opt/chj/emacs/.emacs.d

lesskey

(
    umask 077
    mkdir -p tmp .ssh DROP
)

chmod a+wxt,g+s DROP
touch .ssh/authorized_keys
chmod go-w .ssh/authorized_keys

set +x
echo done.
